[package]
name = "good-web-game"
version = "0.1.0"
authors = ["not-fl3 <not.fl3@gmail.com>"]
license = "MIT/Apache-2.0"
edition = "2018"

[dependencies]
bitflags = "1.1.0"
rustc-hash = "1.0.1"
lazy_static = "1.3.0"
mint = "0.5"
smart-default = "0.3"
cgmath = { version = "0.17", features = ["mint"] }
nalgebra = { version = "0.18", features = ["mint", "stdweb"], optional = true }
stdweb = "0.4.12"
webgl_stdweb = { git = "https://github.com/not-fl3/gl-rs.git", default-features = false }
